// flow-typed signature: 2c36292097a1ff9884b20026ce533bbd
// flow-typed version: <<STUB>>/@material-ui/system_v^4.4.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/system/borders' {
  declare module.exports: any;
}

declare module '@material-ui/system/breakpoints' {
  declare module.exports: any;
}

declare module '@material-ui/system/compose' {
  declare module.exports: any;
}

declare module '@material-ui/system/css' {
  declare module.exports: any;
}

declare module '@material-ui/system/display' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/borders' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/breakpoints' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/compose' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/css' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/display' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/flexbox' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/index' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/memoize' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/merge' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/palette' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/positions' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/responsivePropType' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/shadows' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/sizing' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/spacing' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/style' {
  declare module.exports: any;
}

declare module '@material-ui/system/es/typography' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/borders' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/breakpoints' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/compose' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/css' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/display' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/flexbox' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/index' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/memoize' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/merge' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/palette' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/positions' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/responsivePropType' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/shadows' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/sizing' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/spacing' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/style' {
  declare module.exports: any;
}

declare module '@material-ui/system/esm/typography' {
  declare module.exports: any;
}

declare module '@material-ui/system/flexbox' {
  declare module.exports: any;
}

declare module '@material-ui/system/memoize' {
  declare module.exports: any;
}

declare module '@material-ui/system/merge' {
  declare module.exports: any;
}

declare module '@material-ui/system/palette' {
  declare module.exports: any;
}

declare module '@material-ui/system/positions' {
  declare module.exports: any;
}

declare module '@material-ui/system/responsivePropType' {
  declare module.exports: any;
}

declare module '@material-ui/system/shadows' {
  declare module.exports: any;
}

declare module '@material-ui/system/sizing' {
  declare module.exports: any;
}

declare module '@material-ui/system/spacing' {
  declare module.exports: any;
}

declare module '@material-ui/system/style' {
  declare module.exports: any;
}

declare module '@material-ui/system/typography' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/system/borders.js' {
  declare module.exports: $Exports<'@material-ui/system/borders'>;
}
declare module '@material-ui/system/breakpoints.js' {
  declare module.exports: $Exports<'@material-ui/system/breakpoints'>;
}
declare module '@material-ui/system/compose.js' {
  declare module.exports: $Exports<'@material-ui/system/compose'>;
}
declare module '@material-ui/system/css.js' {
  declare module.exports: $Exports<'@material-ui/system/css'>;
}
declare module '@material-ui/system/display.js' {
  declare module.exports: $Exports<'@material-ui/system/display'>;
}
declare module '@material-ui/system/es/borders.js' {
  declare module.exports: $Exports<'@material-ui/system/es/borders'>;
}
declare module '@material-ui/system/es/breakpoints.js' {
  declare module.exports: $Exports<'@material-ui/system/es/breakpoints'>;
}
declare module '@material-ui/system/es/compose.js' {
  declare module.exports: $Exports<'@material-ui/system/es/compose'>;
}
declare module '@material-ui/system/es/css.js' {
  declare module.exports: $Exports<'@material-ui/system/es/css'>;
}
declare module '@material-ui/system/es/display.js' {
  declare module.exports: $Exports<'@material-ui/system/es/display'>;
}
declare module '@material-ui/system/es/flexbox.js' {
  declare module.exports: $Exports<'@material-ui/system/es/flexbox'>;
}
declare module '@material-ui/system/es/index.js' {
  declare module.exports: $Exports<'@material-ui/system/es/index'>;
}
declare module '@material-ui/system/es/memoize.js' {
  declare module.exports: $Exports<'@material-ui/system/es/memoize'>;
}
declare module '@material-ui/system/es/merge.js' {
  declare module.exports: $Exports<'@material-ui/system/es/merge'>;
}
declare module '@material-ui/system/es/palette.js' {
  declare module.exports: $Exports<'@material-ui/system/es/palette'>;
}
declare module '@material-ui/system/es/positions.js' {
  declare module.exports: $Exports<'@material-ui/system/es/positions'>;
}
declare module '@material-ui/system/es/responsivePropType.js' {
  declare module.exports: $Exports<'@material-ui/system/es/responsivePropType'>;
}
declare module '@material-ui/system/es/shadows.js' {
  declare module.exports: $Exports<'@material-ui/system/es/shadows'>;
}
declare module '@material-ui/system/es/sizing.js' {
  declare module.exports: $Exports<'@material-ui/system/es/sizing'>;
}
declare module '@material-ui/system/es/spacing.js' {
  declare module.exports: $Exports<'@material-ui/system/es/spacing'>;
}
declare module '@material-ui/system/es/style.js' {
  declare module.exports: $Exports<'@material-ui/system/es/style'>;
}
declare module '@material-ui/system/es/typography.js' {
  declare module.exports: $Exports<'@material-ui/system/es/typography'>;
}
declare module '@material-ui/system/esm/borders.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/borders'>;
}
declare module '@material-ui/system/esm/breakpoints.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/breakpoints'>;
}
declare module '@material-ui/system/esm/compose.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/compose'>;
}
declare module '@material-ui/system/esm/css.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/css'>;
}
declare module '@material-ui/system/esm/display.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/display'>;
}
declare module '@material-ui/system/esm/flexbox.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/flexbox'>;
}
declare module '@material-ui/system/esm/index.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/index'>;
}
declare module '@material-ui/system/esm/memoize.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/memoize'>;
}
declare module '@material-ui/system/esm/merge.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/merge'>;
}
declare module '@material-ui/system/esm/palette.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/palette'>;
}
declare module '@material-ui/system/esm/positions.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/positions'>;
}
declare module '@material-ui/system/esm/responsivePropType.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/responsivePropType'>;
}
declare module '@material-ui/system/esm/shadows.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/shadows'>;
}
declare module '@material-ui/system/esm/sizing.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/sizing'>;
}
declare module '@material-ui/system/esm/spacing.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/spacing'>;
}
declare module '@material-ui/system/esm/style.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/style'>;
}
declare module '@material-ui/system/esm/typography.js' {
  declare module.exports: $Exports<'@material-ui/system/esm/typography'>;
}
declare module '@material-ui/system/flexbox.js' {
  declare module.exports: $Exports<'@material-ui/system/flexbox'>;
}
declare module '@material-ui/system/index' {
  declare module.exports: $Exports<'@material-ui/system'>;
}
declare module '@material-ui/system/index.js' {
  declare module.exports: $Exports<'@material-ui/system'>;
}
declare module '@material-ui/system/memoize.js' {
  declare module.exports: $Exports<'@material-ui/system/memoize'>;
}
declare module '@material-ui/system/merge.js' {
  declare module.exports: $Exports<'@material-ui/system/merge'>;
}
declare module '@material-ui/system/palette.js' {
  declare module.exports: $Exports<'@material-ui/system/palette'>;
}
declare module '@material-ui/system/positions.js' {
  declare module.exports: $Exports<'@material-ui/system/positions'>;
}
declare module '@material-ui/system/responsivePropType.js' {
  declare module.exports: $Exports<'@material-ui/system/responsivePropType'>;
}
declare module '@material-ui/system/shadows.js' {
  declare module.exports: $Exports<'@material-ui/system/shadows'>;
}
declare module '@material-ui/system/sizing.js' {
  declare module.exports: $Exports<'@material-ui/system/sizing'>;
}
declare module '@material-ui/system/spacing.js' {
  declare module.exports: $Exports<'@material-ui/system/spacing'>;
}
declare module '@material-ui/system/style.js' {
  declare module.exports: $Exports<'@material-ui/system/style'>;
}
declare module '@material-ui/system/typography.js' {
  declare module.exports: $Exports<'@material-ui/system/typography'>;
}
